# Generated by Django 4.0.1 on 2023-04-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('isbn13', models.IntegerField()),
                ('isbn10', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('pubyear', models.IntegerField()),
                ('subjects', models.CharField(max_length=100)),
                ('lexile', models.CharField(blank=True, max_length=100, null=True)),
                ('pages', models.IntegerField()),
                ('dimensions', models.CharField(max_length=100)),
            ],
        ),
    ]
