# Generated by Django 4.0.1 on 2023-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn13',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='pubyear',
            field=models.CharField(max_length=100),
        ),
    ]
